 =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://bluemeet.cbeewj0wx9bp.us-east-1.rds.amazonaws.com:3306/bluemeet?serverTimezone=UTC&useSSL=false
    username: adminadmin